### ISSUE TITLE
开启去跳转后，贴吧链接跳转受阻

### ISSUE THREAD

**Issue by ghost** [axetroy/GMscript#7]
你好，我使用了大神你的油猴脚本remove the jump link in BAIDU，
使用后功能正常，但是在tieba.baidu.com下访问页面内链接时，总是会卡在
http://jump.bdimg.com/safecheck/index?url=x+Z5mMbGPAs95UolpNuq+CwM2BpViN6QF0BYrUCVRu8Xsvly4TJAae2asJ8Wx3a56kiAGWLXh0hQdflSa3/PJ2pP9nVE2oEE479ByiubzIKODUXA2z6FNRDBASm2xUCIY+KRGwze4NVWZhAVR4xoKDA8Zu4mdgY0

类似这样的地址上，搞的我只能复制原始地址来访问，非常不方便，不知大神可否帮忙解决下？

**Comment by axetroy** [comment]
@LC-BX 
好久没更新了，失效是肯定的
主要是，我已经好久不用百度搜索了，不怎么关心...
目前没有更新的打算。

可能会在未来1个月重构这个

**Comment by ghost** [comment]
@axetroy 收到，谢了，没失效，我又试了试也不是您这个脚本的问题
